"""Coefficients of :func:`ggah_mod.cosmology.drag.z_drag`.

Generated by ``tools/calibrate_zdrag.py`` (seed 20261001); do not edit.
Rerun that script after any change to CLASS, to its BBN table, or to
:func:`~ggah_mod.cosmology.power.class_input`.
"""

#: Total degree of the polynomial in ``drag.FEATURES``.
DEGREE = 3

#: Feature centres, in ``drag.FEATURES`` order.
CENTRE = (0.0224, 0.143, 2.7255, 0.06)

#: Coefficients, in ``drag.terms(DEGREE)`` order.
COEFFS = [1059.9983066589398,
 48.86684331940864,
 10.777136188932005,
 -1240.855495310144,
 0.05359242712336427,
 6.8576477309773365,
 -5.69078352342183,
 -71.35753713860052,
 -0.012997491236174738,
 3.010686207246035,
 -12.391101097245796,
 -0.042872295579854905,
 762.1145156915296,
 -0.8533960749812888,
 0.3729143364815259,
 0.6781249815972561,
 0.5444915222214214,
 -13.329619526933852,
 0.012084691546809325,
 -1.3498373052032013,
 11.095109528396689,
 0.0530192978472444,
 78.66860130197331,
 -1.5279330640414124,
 -0.16457334624506542,
 0.5229319790148802,
 -4.2564117101663665,
 0.014666123736844032,
 -3.7442990010342205,
 0.3337137226867616,
 -0.1332241206795302,
 1504.7381483246295,
 -12.1869416046801,
 2.1833077366528593,
 -0.11335642644794683]

#: The box the fit was calibrated and validated on; ``drag.check_drag_domain``
#: refuses outside it.
BOX = {'omega_b': (0.017, 0.028),
 'omega_cdm': (0.05, 0.3),
 'h': (0.55, 0.85),
 'sum_mnu': (0.0, 0.6),
 'w0': (-1.5, -0.5),
 'wa': (-1.0, 0.6),
 'Omega_k': (-0.15, 0.15),
 'T_cmb': (2.698245, 2.752755)}

#: And inside it, only where dark energy is below this share of the density at
#: z = 1060 (``drag.dark_energy_fraction_at_drag``).  Beyond it the fit
#: misses CLASS by up to 2 in z_d; it excludes
#: 4.2% of the box above.
F_DE_MAX = 0.001

#: The accuracy reached, against CLASS v3.3.4.
VALIDATION = {'target_abs_dz_heldout': 0.02,
 'target_abs_dz_corners': 0.05,
 'n_fit': 1915,
 'n_heldout': 485,
 'n_corners': 192,
 'n_corners_refused_by_class': 0,
 'fraction_of_box_excluded_by_f_de': 0.04249999999999998,
 'max_abs_dz_heldout': 0.016956165402916668,
 'rms_dz_heldout': 0.0047987522622127896,
 'max_abs_dz_corners': 0.028844997569876796,
 'max_abs_dz_excluded_heldout': 1.9977467913081455,
 'max_abs_dlnrd_vs_class': 5.713701310664432e-05,
 'max_abs_dlnrd_vs_class_flat': 4.505342034479418e-06,
 'max_abs_dlnrd_integral_at_class_zd': 6.55015030520723e-05,
 'max_abs_dlnrd_integral_at_class_zd_flat': 2.1507817110582946e-06,
 'rs_d_fiducial_class_mpc': 147.73933678628515,
 'z_d_fiducial_class': 1059.706148916211}

#: Every assumption behind the helium fraction CLASS used, read from CLASS and
#: its table at calibration time.
BBN = {'class_version': 'v3.3.4',
 'recombination': 'CLASS default (HyRec-2: Lee & Ali-Haimoud 2020; Ali-Haimoud & '
                  'Hirata 2011)',
 'sbbn_file': '/external/bbn/sBBN_2017.dat',
 'sbbn_header': ['standard BBN prediction for primordial Helium mass fraction $Y_p$ as',
                 'function of the baryon density $\\omega_b h^2$ and number of extra',
                 'radiation degrees of freedom $\\Delta N = N_eff-3.046$. Impact of',
                 'chemical potential of electron neutrinos neglected in this version.',
                 'Calculated with PArthENoPE v1.2 for a neutron lifetime of 880.2 s,',
                 'identical to standard assumptions of Planck 2017 papers.'],
 'bbn_code': 'PArthENoPE v1.2',
 'neutron_lifetime_s': 880.2,
 'helium_quantity': "mass fraction YHe, read from the table's third column with no "
                    'Y_p^BBN conversion',
 'n_eff': 3.044,
 'delta_n_looked_up': -0.002,
 'delta_n_convention': 'CLASS measures N_eff at T = 0.1 MeV from the background and '
                       "subtracts 3.046, the table's reference "
                       '(thermodynamics_helium_from_bbn)',
 't_cmb_rescaling': 'none: CLASS interpolates the table at omega_b as given; CAMB '
                    'rescales omega_b by (2.7255/T_cmb)^3',
 'standard_bbn': 'no electron-neutrino chemical potential; constants not varied',
 'YHe_fiducial': 0.24536815009196056,
 'dzd_dYHe': 34.75204598851178,
 'dlnrd_dYHe': -0.021434322492636024,
 'YHe_range_in_box': [0.24267241158783065, 0.24748847343093527]}
